name : NASA Project CI
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node-js version 16
        uses: actions/setup-node@v2
        with: 
          node-version : '16'
      - run: cd .. && cd .. && cd client && npm run build